### ISSUE TITLE
Build question

### ISSUE THREAD

**Issue by nolaandy** [Enterwell/wp-vladimir#1]
I'm just getting into this stuff.  I'm trying to build the bundle file to get this to work, since I'm just getting a blank homepage right now.

When I type "webpack" in the /react folder I get this error:

> $ webpack
Hash: 15ec0fc53eded293a44d
Version: webpack 1.13.2
Time: 741ms
   [0] multi main 64 bytes {0} [built] [1 error]
    + 260 hidden modules
ERROR in multi main
Module not found: Error: Cannot resolve 'file' or 'directory' C:\wamp\www\1\wp-content\themes\wp-vladimir\react\react\src\index in C:\wamp\www\1\wp-content\themes\wp-vladimir\react
 @ multi main

I saw that it appears to reach /react/react  -  it should just be /react

I tried removing /react from the module exports in webpack.config.dev.js but it gave me further errors.

Am I supposed to be building a different way? I saw you have Gulp as a dependency. Do you build via a gulp file that isn't included? Thanks in advance.

**Comment by gliba008** [comment]
Hi @nolaandy 😄
Try building it by calling `npm start`. It will set the development value to process.env,NODE_ENV and start the development webpack config.

For this React example you don't need gulp. This is simplified version from what we normally use in projects so we have a couple of leftovers (gulp, etc.). We hope to clean this up a bit as soon as we catch a little bit of free time 😄.
